name: dory
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  fonts:
    - family: GmarketSansTTF
      fonts:
        - asset: assets/fonts/gmarket/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/gmarket/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/gmarket/GmarketSansTTFBold.ttf
          weight: 700